
###
POST http://localhost:3000/users
Content-Type: application/json

{ 
    "firstName": "firstName",
    "lastName": "lastName",
    "email": "email@email.com",
    "password": "password"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{ 
    "email": "email@email.com",
    "password": "password"
}

###
POST http://localhost:3000/identity/process
Content-Type: application/json
Authorization: Bearer 

{ 
    "bvn": "11111111111"
}

###
GET http://localhost:3000/customers
Content-Type: application/json
Authorization: Bearer 
