# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl = http://localhost:3000
# @baseUrl = https://okra-shapel.vercel.app

# @name register
POST {{baseUrl}}/users
Content-Type: application/json

{ 
    "firstName": "firstName",
    "lastName": "lastName",
    "email": "email@email.com",
    "password": "password"
}

###

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{ 
    "email": "email@email.com",
    "password": "password"
}

###

@authToken = {{login.response.body.$.access_token}}

###
POST {{baseUrl}}/identity/process
Content-Type: application/json
Authorization: Bearer {{authToken}}

{ 
    "bvn": "11111111111"
}


###

# @name getCustomers
GET {{baseUrl}}/customers
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name getCustomer
GET {{baseUrl}}/customers/{{getCustomers.response.body.$[0][id]}}
Content-Type: application/json
Authorization: Bearer {{authToken}}
